### ISSUE TITLE
Arguments are empty

### ISSUE THREAD

**Issue by BigtornG** [PhantomGamers/SFP#136] opened 2023-06-23 03:05 UTC
Every time I try injecting the skin and teaks I want for steam, I get this error.

I have the latest version of SFP and Old Glory as well.

https://gyazo.com/9a6804f0d3c10e3023467b7dcf7c13f8

Steam is running in - cef -enable-debugging

**Comment by PhantomGamers** [comment] 2023-06-23 03:52
What happens if you click restart steam?

**Comment by BigtornG** [comment] 2023-06-23 05:47
SFP just stops responding and closest

**Comment by PhantomGamers** [comment] 2023-06-23 06:02
> SFP just stops responding and closest

Post the SFP.log after this happens

**Comment by BigtornG** [comment] 2023-06-23 06:08
[](url)
[SFP.log](https://github.com/PhantomGamers/SFP/files/11844586/SFP.log)

**Comment by PhantomGamers** [comment] 2023-06-23 06:09
This log doesn't show that it's crashed or that you clicked Restart steam at all, just that you closed it normally.

**Comment by BigtornG** [comment] 2023-06-23 06:11
https://gyazo.com/f11bde84c572d1c0540fd6cda74c330f

**Comment by BigtornG** [comment] 2023-06-23 06:11
[SFP.log](https://github.com/PhantomGamers/SFP/files/11844613/SFP.log)

**Comment by PhantomGamers** [comment] 2023-06-23 06:13
Do you have Steam running as admin or something? If you run SFP as admin does the same issue occur?

**Comment by BigtornG** [comment] 2023-06-23 06:14
yes I run it on admin and my settings keep resetting as well.

**Comment by BigtornG** [comment] 2023-06-23 06:15
same error keeps happening

**Comment by PhantomGamers** [comment] 2023-06-23 06:16
You shouldn't be running Steam as admin tbh, that's causing issues here. Running Steam as admin should never be necessary, and at best it opens you up to malware attacks.

The settings resetting is a different problem, are you talking about the SFP settings? Where do you have SFP extracted to?

SFP relies on the SFP.config file that gets stored in the same folder as SFP_UI.exe, if it can't write to this for some reason, such as if it doesn't have permission to write to the folder you installed it to, it will fail.

**Comment by BigtornG** [comment] 2023-06-23 06:18
I shouldn't be running Steam as admin? alright i'll do it without admin

**Comment by BigtornG** [comment] 2023-06-23 06:19
I have SFP extracted to it's own folder on the desktop

**Comment by BigtornG** [comment] 2023-06-23 06:19
ok so this is weird, running it as admin make SFP worked but I'm worried how to get it to work without admin and to keep the settings.

**Comment by PhantomGamers** [comment] 2023-06-23 06:20
If Steam isn't running as admin, SFP doesn't need to run as admin.

**Comment by BigtornG** [comment] 2023-06-23 06:20
ok ill check one sec

**Comment by BigtornG** [comment] 2023-06-23 06:21
yea the settings didn't save after restarting steam

**Comment by BigtornG** [comment] 2023-06-23 06:21
and i ran it without admin

**Comment by BigtornG** [comment] 2023-06-23 06:24
did that and am getting the same errors again

**Comment by BigtornG** [comment] 2023-06-23 06:25
https://gyazo.com/8d34ef54f7d2f7f04ee03601ae3d439c

**Comment by PhantomGamers** [comment] 2023-06-23 06:25
is Steam running as admin again?

**Comment by BigtornG** [comment] 2023-06-23 06:25
nope

**Comment by BigtornG** [comment] 2023-06-23 06:25
and the extractor program was not run on admin as well

**Comment by PhantomGamers** [comment] 2023-06-23 06:26
I think you've messed something up with your system lol. Why were you running Steam as admin in the first place, and what else have you been doing with permissions?

**Comment by BigtornG** [comment] 2023-06-23 06:27
Well Originally I wasn't running steam as admin and it didn't work, than I did try it to see if SFP would work and it did, but you told me it wasn't safe so now I'm doing it without admin and now I'm getting the same errors

**Comment by BigtornG** [comment] 2023-06-23 06:27
i didn't have these problems till recently so not sure what wrong is my system that I messed up

**Comment by BigtornG** [comment] 2023-06-23 06:28
i rarely run much stuff with permissions, only did it here to see the errors would go away

**Comment by BigtornG** [comment] 2023-06-23 06:29
keep getting the same 2 errors from the screenshot

**Comment by PhantomGamers** [comment] 2023-06-23 06:30
Well the reason it's not working is that SFP doesn't have permission to access the Steam process. On normal systems, it should have access without needing admin, but in your case cuz of something that was done on your machine, Steam seems to be running as admin.

I don't really know what to suggest, if it was me I'd just nuke my whole Windows install and start clean lol. Cuz if SFP doesn't even have permission to write to a subfolder on your desktop for the config file something's really messed up. But if running SFP as admin works you can just do that I guess

**Comment by BigtornG** [comment] 2023-06-23 06:30
arguments are empty and could not fetch browser

**Comment by BigtornG** [comment] 2023-06-23 06:31
well it was working before the new update so I'm not sure why it's not working now. Makes no sense I didn't change anything

**Comment by BigtornG** [comment] 2023-06-23 06:31
also even if it does work the settings don't save when I restart steam

**Comment by PhantomGamers** [comment] 2023-06-23 06:32
Arguments are empty = SFP does not have permission to access the Steam process' arguments
Could not fetch browser = Steam is not running with -cef-enable-debugging, or another service is running on port 8080
Settings not saving = SFP does not have permission to write to SFP.config in the same folder as SFP_UI.exe
The crash you were getting is caused by this error:
> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32, Int32, Boolean)
   at System.Diagnostics.Process.GetProcessHandle(Int32, Boolean )
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.EnsureWatchingForExit()
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean)
   at SFP.Models.Steam.RestartSteam(String ) in D:\a\SFP\SFP\SFP\Models\Steam.cs:line 243
Which is again caused by SFP not having permission to enable raising events on the Steam process

**Comment by BigtornG** [comment] 2023-06-23 06:32
so what should I do?

**Comment by PhantomGamers** [comment] 2023-06-23 06:32
Just run SFP as admin

**Comment by BigtornG** [comment] 2023-06-23 06:32
idk if it's my fire wall doing something to it

**Comment by PhantomGamers** [comment] 2023-06-23 06:33
Firewalls are for network traffic, the problems you're running into are caused by local permission problems

**Comment by BigtornG** [comment] 2023-06-23 06:34
ok i am trying running SFP as admin, didn't you say that was dangerous?

**Comment by PhantomGamers** [comment] 2023-06-23 06:34
No, I said running Steam as admin is dangerous, and it both is dangerous and appears to be running as admin

**Comment by BigtornG** [comment] 2023-06-23 06:35
So running SFP as admin is fine and safe  then?

**Comment by PhantomGamers** [comment] 2023-06-23 06:36
I mean it's safe, but normally should not be needed and is not recommended

**Comment by BigtornG** [comment] 2023-06-23 06:39
settings didn't save

**Comment by BigtornG** [comment] 2023-06-23 06:47
does this not work with old steam UI?

**Comment by PhantomGamers** [comment] 2023-06-23 06:57
It does but it's made for the new UI and I won't be offering support for the old UI.

I'm just gonna close this issue cuz it's not really an issue with SFP but with your system, nothing I can do in SFP to fix it.

I did add a catch for the crash at least so that part will be fixed in the next release, but it won't make it work or anything.

**Closed by PhantomGamers** 2023-06-23 06:57 UTC

**Comment by BigtornG** [comment] 2023-06-23 06:58
so it does work?

**Comment by BigtornG** [comment] 2023-06-23 06:59
can you please explain how it still does work

**Comment by BigtornG** [comment] 2023-06-23 07:01
i would like to use the custom skin with the old UI
